### ISSUE TITLE
Error while starting HAL 

### ISSUE THREAD

**Issue by charlieleprince** [adareau/HAL#34]
```
15:50:05] - HAL.classes.settings - WARNING - ERROR IN SETTINGS LOADER
[15:50:05] - HAL.classes.settings - WARNING - >> '/home/charlie/.HAL/global.conf' do not exist
Traceback (most recent call last):
  File "start", line 23, in <module>
    window = MainWindow()
  File "/home/charlie/HAL/HAL/gui/main.py", line 191, in __init__
    self.setupElements()
  File "/home/charlie/HAL/HAL/gui/main.py", line 229, in setupElements
    advancedplot.setupAdvancedPlot(self)
  File "/home/charlie/HAL/HAL/gui/advancedplot.py", line 224, in setupAdvancedPlot
    for content in saved_config_folder.iterdir():
  File "/usr/lib/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/home/charlie/.HAL/advanced_plot_saved_configurations'
```

**Comment by adareau** [comment]
The "advanced_plot_saved_configurations" in ~/.HAL is used to store plot configurations. HAL browses this folder to display the available plot configurations in a dedicated comboBox. It should handle the case were the folder does not exist !!

**Comment by adareau** [comment]
should be OK now :)

**Comment by quentinmarolleau** [comment]
I had the same issue, and fixed it by creating the required folders if there weren't existing.
We have a similar "issue" with:
```
[11:05:54] - HAL.classes.settings - WARNING - ERROR IN SETTINGS LOADER
[11:05:54] - HAL.classes.settings - WARNING - >> '/home/quentin/.HAL/global.conf' do not exist
```
That can be easily solved by 
```
if not os.path.exists('kek'):
    with open('kek', 'w'): pass
```
but I'm wondering after all if we do not want to keep the error message to pin point the fact that the complete config file is missing. Otherwise we need to generate a default one is it's missing at startup.

**Comment by adareau** [comment]
The current version is already checking whether the file exists. The logger issues a warning (not an error!) when the setting file is not found, so that the user knows default settings are loaded. As would the wise man say: it's a feature, not a bug
