### ISSUE TITLE
Error while opening an image

### ISSUE THREAD

**Issue by charlieleprince** [adareau/HAL#44]
When I open any image I get the following error message:

```
Traceback (most recent call last):
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 462, in paint
    self.render()
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 451, in render
    fn.makeARGB(image, lut=lut, levels=levels, output=self._processingBuffer)
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/functions.py", line 1218, in makeARGB
    raise Exception('levels argument is required for float input types')
Exception: levels argument is required for float input types
Traceback (most recent call last):
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 462, in paint
    self.render()
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 451, in render
    fn.makeARGB(image, lut=lut, levels=levels, output=self._processingBuffer)
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/functions.py", line 1218, in makeARGB
    raise Exception('levels argument is required for float input types')
Exception: levels argument is required for float input types
Traceback (most recent call last):
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 462, in paint
    self.render()
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 451, in render
    fn.makeARGB(image, lut=lut, levels=levels, output=self._processingBuffer)
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/functions.py", line 1218, in makeARGB
    raise Exception('levels argument is required for float input types')
Exception: levels argument is required for float input types
Traceback (most recent call last):
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 462, in paint
    self.render()
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 451, in render
    fn.makeARGB(image, lut=lut, levels=levels, output=self._processingBuffer)
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/functions.py", line 1218, in makeARGB
    raise Exception('levels argument is required for float input types')
Exception: levels argument is required for float input types
Traceback (most recent call last):
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 462, in paint
    self.render()
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 451, in render
    fn.makeARGB(image, lut=lut, levels=levels, output=self._processingBuffer)
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/functions.py", line 1218, in makeARGB
    raise Exception('levels argument is required for float input types')
Exception: levels argument is required for float input types
Traceback (most recent call last):
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 462, in paint
    self.render()
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 451, in render
    fn.makeARGB(image, lut=lut, levels=levels, output=self._processingBuffer)
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/functions.py", line 1218, in makeARGB
    raise Exception('levels argument is required for float input types')
Exception: levels argument is required for float input types
Traceback (most recent call last):
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 462, in paint
    self.render()
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 451, in render
    fn.makeARGB(image, lut=lut, levels=levels, output=self._processingBuffer)
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/functions.py", line 1218, in makeARGB
    raise Exception('levels argument is required for float input types')
Exception: levels argument is required for float input types
Traceback (most recent call last):
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 462, in paint
    self.render()
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 451, in render
    fn.makeARGB(image, lut=lut, levels=levels, output=self._processingBuffer)
  File "/home/charlie/.local/lib/python3.8/site-packages/pyqtgraph/functions.py", line 1218, in makeARGB
    raise Exception('levels argument is required for float input types')
Exception: levels argument is required for float input types
```
Despite this everything seems to work fine. I guess it has to do with [this pyqtgraph function](https://pyqtgraph.readthedocs.io/en/latest/_modules/pyqtgraph/functions.html) ?

**Comment by adareau** [comment]
OK, so this only seems to happen when we open an image with no saved fit...

**Comment by adareau** [comment]
also, not with the "image only" display mode >>> it has to do with the panels showing the fits I guess !!

**Comment by adareau** [comment]
#45 should fix it. @charlieleprince, can you confirm ?

**Comment by charlieleprince** [comment]
Yes I do! No more error message here, thank you.

By the way, isn't that weird that the error message mentions the pyqtgraph package from python3.8 located in .local/lib while I run HAL from a virtual environment?
