### ISSUE TITLE
Error while installing HAL

### ISSUE THREAD

**Issue by charlieleprince** [adareau/HAL#74]
Hi,

I tried to reinstall HAL (core only so far) but I get an error message while trying to start the program. There must be a bug in the setup parameters?
```
Traceback (most recent call last):
  File "./start", line 52, in <module>
    main(args, sys.argv)
  File "./start", line 45, in main
    window = MainWindow(debug=args.debug)
  File "/home/charlie/HAL/HAL/gui/main.py", line 241, in __init__
    self.setupElements()
  File "/home/charlie/HAL/HAL/gui/main.py", line 350, in setupElements
    display.setupDisplay(self)
  File "/home/charlie/HAL/HAL/gui/display.py", line 62, in setupDisplay
    default_display_name = list(self.display_classes)[0]
IndexError: list index out of range
```

**Comment by adareau** [comment]
should work now. @charlieleprince, can you confirm this is fine now ?

**Comment by charlieleprince** [comment]
All good! Thanks.
